# Generated by Django 5.1.1 on 2024-10-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0003_individual_remove_ticketcomment_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='groups', to='a_users.individual')),
            ],
        ),
    ]
