# Generated by Django 5.1.1 on 2024-10-22 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSatisfactionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('pay', 'Pay'), ('promotion', 'Promotion'), ('supervision', 'Supervision'), ('fringe_benefits', 'Fringe Benefits'), ('contingent_rewards', 'Contingent Rewards'), ('operating_conditions', 'Operating Conditions'), ('coworkers', 'Coworkers'), ('nature_of_work', 'Nature of Work'), ('communication', 'Communication'), ('health_and_safety', 'Health and Safety')], max_length=50)),
                ('required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('age_group', models.CharField(choices=[('20_below', '20yrs and below'), ('21_30', '21-30yrs'), ('31_40', '31-40yrs'), ('41_50', '41-50yrs'), ('51_60', '51-60yrs')], max_length=10)),
                ('work_experience', models.CharField(choices=[('5_below', '5yrs and below'), ('6_9', '6-9yrs'), ('10_19', '10-19yrs'), ('20_above', '20 and above')], max_length=10)),
                ('highest_qualification', models.CharField(choices=[('below_o', 'Below O’ level'), ('o_level', 'O’ level'), ('a_level', 'A’ level'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Post-graduate')], max_length=20)),
                ('designation', models.CharField(choices=[('senior_management', 'Senior Management'), ('professional_employees', 'Professional Employees'), ('middle_management', 'Middle Management'), ('line_employees', 'Line Employees')], max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('contract_type', models.CharField(choices=[('fixed_term', 'Fixed –Term Contract'), ('permanent', 'Permanent Contract')], max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikertScaleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(1, 'Disagree very much'), (2, 'Disagree moderately'), (3, 'Disagree slightly'), (4, 'Agree slightly'), (5, 'Agree moderately'), (6, 'Agree very much')])),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='a_home.jobsatisfactionquestion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
