# Generated by Django 5.1.1 on 2024-10-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('DEV', 'Development')], default='MKT', max_length=100),
        ),
    ]
