# Generated by Django 5.1.1 on 2024-10-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_alter_demographicdata_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='age_group',
            field=models.CharField(choices=[('20_below', '20yrs and below'), ('21_30', '21-30yrs'), ('31_40', '31-40yrs'), ('41_50', '41-50yrs'), ('51_60', '51-60yrs')], default='20_below', max_length=10),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='contract_type',
            field=models.CharField(choices=[('fixed_term', 'Fixed –Term Contract'), ('permanent', 'Permanent Contract')], default='permanent', max_length=15),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='designation',
            field=models.CharField(choices=[('senior_management', 'Senior Management'), ('professional_employees', 'Professional Employees'), ('middle_management', 'Middle Management'), ('line_employees', 'Line Employees')], default='line_employees', max_length=30),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='highest_qualification',
            field=models.CharField(choices=[('below_o', 'Below O’ level'), ('o_level', 'O’ level'), ('a_level', 'A’ level'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Post-graduate')], default='o_level', max_length=20),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='work_experience',
            field=models.CharField(choices=[('5_below', '5yrs and below'), ('6_9', '6-9yrs'), ('10_19', '10-19yrs'), ('20_above', '20 and above')], default='5_below', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobsatisfactionquestion',
            name='category',
            field=models.CharField(choices=[('pay', 'Pay'), ('promotion', 'Promotion'), ('supervision', 'Supervision'), ('fringe_benefits', 'Fringe Benefits'), ('contingent_rewards', 'Contingent Rewards'), ('operating_conditions', 'Operating Conditions'), ('coworkers', 'Coworkers'), ('nature_of_work', 'Nature of Work'), ('communication', 'Communication'), ('health_and_safety', 'Health and Safety'), ('vigour_energy', 'Vigour and Energy'), ('dedication', 'Dedication'), ('absorption', 'Absorption')], max_length=50),
        ),
    ]
