# Generated by Django 5.1.1 on 2024-10-22 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0003_alter_demographicdata_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicdata',
            name='response_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 22, 10, 36, 29, 183180, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
